name: Build & deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  deploy-bump-version:
    name: Bump version and Deploy 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_ACTION }}
          persist-credentials: false

      - name: Automated Version Bump
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.TOKEN_ACTION }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          release-count: 0
          skip-on-empty: false
          tag-prefix: ''
          output-file: 'CHANGELOG.md'

      - name: Install and Build
        run: |
          yarn install
          yarn build-storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: .

      - name: Checkout Git repo/update
        run: git pull origin main

      - name: Install depends
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Deploy NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
