name: Lint/Prettier Code Base

on: pull_request

jobs:
 run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Configure git
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_ACTION }}

      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.2
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true

      - name: Run tests
        run: yarn test
