name: Deploy Storybook
on:
  push:
    branches:
      - feature/required-id
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          dir: storybook-static
          token: ${{ secrets.ACCESS_TOKEN }}
